const answer_result = [
  {
    name: "Siswa 1",
    quiz: "1 + 1 = ...",
    quiz_id: 1,
    answer_essay: null,
  },
  {
    name: "Siswa 1",
    quiz: "2 + 2 = ...",
    quiz_id: 2,
    answer_essay: null,
  },
  {
    name: "Siswa 1",
    quiz: "2 + 1 = ...",
    quiz_id: 3,
    answer_essay: null,
  },
  {
    name: "Siswa 1",
    quiz: "2 + 3 = ...",
    quiz_id: 4,
    answer_essay: null,
  },
  {
    name: "Siswa 1",
    quiz: "3 + 3 = ...",
    quiz_id: 5,
    answer_essay: null,
  },
  {
    name: "Siswa 1",
    quiz: "Ibu Kota Indonesia ...",
    quiz_id: 6,
    answer_essay: null,
  },
  {
    name: "Siswa 1",
    quiz: "Ibu Kota Jawa Barat ...",
    quiz_id: 7,
    answer_essay: null,
  },
  {
    name: "Siswa 2",
    quiz: "2 + 2 = ...",
    quiz_id: 2,
    answer_essay: null,
  },
  {
    name: "Siswa 2",
    quiz: "2 + 1 = ...",
    quiz_id: 3,
    answer_essay: null,
  },
  {
    name: "Siswa 2",
    quiz: "2 + 3 = ...",
    quiz_id: 4,
    answer_essay: null,
  },
  {
    name: "Siswa 2",
    quiz: "3 + 3 = ...",
    quiz_id: 5,
    answer_essay: null,
  },
  {
    name: "Siswa 2",
    quiz: "Ibu Kota Indonesia ...",
    quiz_id: 6,
    answer_essay: null,
  },
  {
    name: "Siswa 2",
    quiz: "Ibu Kota Jawa Barat ...",
    quiz_id: 7,
    answer_essay: null,
  },
  {
    name: "Siswa 2",
    quiz: "Jelaskan apa itu integer",
    quiz_id: 8,
    answer_essay: "Bogor",
  },
  {
    name: "Siswa 2",
    quiz: "1 + 1 = ...",
    quiz_id: 1,
    answer_essay: null,
  },
  {
    name: "Siswa 1",
    quiz: "Jelaskan apa itu integer",
    quiz_id: 8,
    answer_essay: "Bilangan Bulat",
  },
];

const quiz = [
  {
    _id: 1,
    exam_id: 3,
    quiz_type: 1,
    quiz: "1 + 1 = ...",
    img: null,
    audio: null,
    answer_1: "2",
    answer_2: "3",
    answer_3: "4",
    answer_4: "5",
    answer_5: "6",
    key: "A",
  },
  {
    _id: 2,
    exam_id: 3,
    quiz_type: 1,
    quiz: "2 + 2 = ...",
    img: null,
    audio: null,
    answer_1: "2",
    answer_2: "3",
    answer_3: "4",
    answer_4: "5",
    answer_5: "6",
    key: "C",
  },
  {
    _id: 3,
    exam_id: 3,
    quiz_type: 1,
    quiz: "2 + 1 = ...",
    img: null,
    audio: null,
    answer_1: "2",
    answer_2: "3",
    answer_3: "4",
    answer_4: "5",
    answer_5: "6",
    key: "B",
  },
  {
    _id: 4,
    exam_id: 3,
    quiz_type: 1,
    quiz: "2 + 3 = ...",
    img: null,
    audio: null,
    answer_1: "2",
    answer_2: "3",
    answer_3: "4",
    answer_4: "5",
    answer_5: "6",
    key: "D",
  },
  {
    _id: 5,
    exam_id: 3,
    quiz_type: 1,
    quiz: "3 + 3 = ...",
    img: null,
    audio: null,
    answer_1: "2",
    answer_2: "3",
    answer_3: "4",
    answer_4: "5",
    answer_5: "6",
    key: "E",
  },
  {
    _id: 6,
    exam_id: 3,
    quiz_type: 1,
    quiz: "Ibu Kota Indonesia ...",
    img: null,
    audio: null,
    answer_1: "Jakarta",
    answer_2: "Bandung",
    answer_3: "Nusantara",
    answer_4: "Jogja",
    answer_5: "Bogor",
    key: "A",
  },
  {
    _id: 7,
    exam_id: 3,
    quiz_type: 1,
    quiz: "Ibu Kota Jawa Barat ...",
    img: null,
    audio: null,
    answer_1: "Jakarta",
    answer_2: "Bandung",
    answer_3: "Nusantara",
    answer_4: "Jogja",
    answer_5: "Bogor",
    key: "E",
  },
  {
    _id: 8,
    exam_id: 3,
    quiz_type: 2,
    quiz: "Jelaskan apa itu integer",
    img: null,
    audio: null,
    answer_1: null,
    answer_2: null,
    answer_3: null,
    answer_4: null,
    answer_5: null,
    key: null,
  },
];
