// EXAM
export const GET_EXAM_REQ = "GET_EXAM_REQ";
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const GET_EXAM_FAIL = "GET_EXAM_FAIL";

export const GET_EXAM_BY_GARDE_REQ = "GET_EXAM_BY_GARDE_REQ";
export const GET_EXAM_BY_GARDE_SUCCESS = "GET_EXAM_BY_GARDE_SUCCESS";
export const GET_EXAM_BY_GARDE_FAIL = "GET_EXAM_BY_GARDE_FAIL";

export const DETAIL_EXAM_REQ = "DETAIL_EXAM_REQ";
export const DETAIL_EXAM_SUCCESS = "DETAIL_EXAM_SUCCESS";
export const DETAIL_EXAM_FAIL = "DETAIL_EXAM_FAIL";
export const DETAIL_EXAM_RESET = "DETAIL_EXAM_RESET";

export const ADD_EXAM_REQ = "ADD_EXAM_REQ";
export const ADD_EXAM_SUCCESS = "ADD_EXAM_SUCCESS";
export const ADD_EXAM_FAIL = "ADD_EXAM_FAIL";
export const ADD_EXAM_RESET = "ADD_EXAM_RESET";

export const UP_EXAM_REQ = "UP_EXAM_REQ";
export const UP_EXAM_SUCCESS = "UP_EXAM_SUCCESS";
export const UP_EXAM_FAIL = "UP_EXAM_FAIL";
export const UP_EXAM_RESET = "UP_EXAM_RESET";

export const DEL_EXAM_REQ = "DEL_EXAM_REQ";
export const DEL_EXAM_SUCCESS = "DEL_EXAM_SUCCESS";
export const DEL_EXAM_FAIL = "DEL_EXAM_FAIL";
export const DEL_EXAM_RESET = "DEL_EXAM_RESET";

// ROOM
export const ADD__ROOM_REQ = "ADD__ROOM_REQ";
export const ADD__ROOM_SUCCESS = "ADD__ROOM_SUCCESS";
export const ADD__ROOM_FAIL = "ADD__ROOM_FAIL";
export const ADD__ROOM_RESET = "ADD__ROOM_RESET";

export const GET_ROOM_REQ = "GET_ROOM_REQ";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";
export const GET_ROOM_FAIL = "GET_ROOM_FAIL";
export const GET_ROOM_RESET = "GET_ROOM_RESET";

export const DETAIL_ROOM_REQ = "DETAIL_ROOM_REQ";
export const DETAIL_ROOM_SUCCESS = "DETAIL_ROOM_SUCCESS";
export const DETAIL_ROOM_FAIL = "DETAIL_ROOM_FAIL";
export const DETAIL_ROOM_RESET = "DETAIL_ROOM_RESET";

export const UP_ROOM_REQ = "UP_ROOM_REQ";
export const UP_ROOM_SUCCESS = "UP_ROOM_SUCCESS";
export const UP_ROOM_FAIL = "UP_ROOM_FAIL";
export const UP_ROOM_RESET = "UP_ROOM_RESET";

export const DEL_ROOM_REQ = "DEL_ROOM_REQ";
export const DEL_ROOM_SUCCESS = "DEL_ROOM_SUCCESS";
export const DEL_ROOM_FAIL = "DEL_ROOM_FAIL";
export const DEL_ROOM_RESET = "DEL_ROOM_RESET";
