export const GET_QUIZ_REQ = "GET_QUIZ_REQ";
export const GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";
export const GET_QUIZ_FAIL = "GET_QUIZ_FAIL";

export const ADD_QUIZ_REQ = "ADD_QUIZ_REQ";
export const ADD_QUIZ_SUCCESS = "ADD_QUIZ_SUCCESS";
export const ADD_QUIZ_FAIL = "ADD_QUIZ_FAIL";
export const ADD_QUIZ_RESET = "ADD_QUIZ_RESET";

export const UPLOAD_QUIZ_REQ = "UPLOAD_QUIZ_REQ";
export const UPLOAD_QUIZ_SUCCESS = "UPLOAD_QUIZ_SUCCESS";
export const UPLOAD_QUIZ_FAIL = "UPLOAD_QUIZ_FAIL";
export const UPLOAD_QUIZ_RESET = "UPLOAD_QUIZ_RESET";

export const EDIT_QUIZ_REQ = "EDIT_QUIZ_REQ";
export const EDIT_QUIZ_SUCCESS = "EDIT_QUIZ_SUCCESS";
export const EDIT_QUIZ_FAIL = "EDIT_QUIZ_FAIL";
export const EDIT_QUIZ_RESET = "EDIT_QUIZ_RESET";

export const DEL_QUIZ_REQ = "DEL_QUIZ_REQ";
export const DEL_QUIZ_SUCCESS = "DEL_QUIZ_SUCCESS";
export const DEL_QUIZ_FAIL = "DEL_QUIZ_FAIL";
export const DEL_QUIZ_RESET = "DEL_QUIZ_RESET";
