export const GET_MY_ANSWER_REQ = "GET_MY_ANSWER_REQ";
export const GET_MY_ANSWER_SUCCESS = "GET_MY_ANSWER_SUCCESS";
export const GET_MY_ANSWER_FAIL = "GET_MY_ANSWER_FAIL";
export const GET_MY_ANSWER_RESET = "GET_MY_ANSWER_RESET";

export const GET_ANSWER_REQ = "GET_ANSWER_REQ";
export const GET_ANSWER_SUCCESS = "GET_ANSWER_SUCCESS";
export const GET_ANSWER_FAIL = "GET_ANSWER_FAIL";
export const GET_ANSWER_RESET = "GET_ANSWER_RESET";

export const CREATE_ANSWER_REQ = "CREATE_ANSWER_REQ";
export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAIL = "CREATE_ANSWER_FAIL";
export const CREATE_ANSWER_RESET = "CREATE_ANSWER_RESET";

export const UPDATE_ANSWER_REQ = "UPDATE_ANSWER_REQ";
export const UPDATE_ANSWER_SUCCESS = "UPDATE_ANSWER_SUCCESS";
export const UPDATE_ANSWER_FAIL = "UPDATE_ANSWER_FAIL";
export const UPDATE_ANSWER_RESET = "UPDATE_ANSWER_RESET";
