export const GET_SUBJECTS_REQ = "GET_SUBJECTS_REQ";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_FAIL = "GET_SUBJECTS_FAIL";

export const ADD_SUBJECT_REQ = "ADD_SUBJECT_REQ";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL";
export const ADD_SUBJECT_RESET = "ADD_SUBJECT_RESET";

export const DEL_SUBJECT_REQ = "DEL_SUBJECT_REQ";
export const DEL_SUBJECT_SUCCESS = "DEL_SUBJECT_SUCCESS";
export const DEL_SUBJECT_FAIL = "DEL_SUBJECT_FAIL";
export const DEL_SUBJECT_RESET = "DEL_SUBJECT_RESET";
