export const STUDENTS_GET_REQ = "STUDENTS_GET_REQ";
export const STUDENTS_GET_SUCCESS = "STUDENTS_GET_SUCCESS";
export const STUDENTS_GET_FAIL = "STUDENTS_GET_FAIL";

export const ADD_STUDENT_REQ = "ADD_STUDENT_REQ";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";
export const ADD_STUDENT_RESET = "ADD_STUDENT_RESET";

export const UPLOAD_STUDENTS_REQ = "UPLOAD_STUDENTS_REQ";
export const UPLOAD_STUDENTS_SUCCESS = "UPLOAD_STUDENTS_SUCCESS";
export const UPLOAD_STUDENTS_FAIL = "UPLOAD_STUDENTS_FAIL";
export const UPLOAD_STUDENTS_RESET = "UPLOAD_STUDENTS_RESET";
