export const STUDENTS_GET_REQ = "STUDENTS_GET_REQ";
export const STUDENTS_GET_SUCCESS = "STUDENTS_GET_SUCCESS";
export const STUDENTS_GET_FAIL = "STUDENTS_GET_FAIL";

export const STUDENTS_BY_GRADE_REQ = "STUDENTS_BY_GRADE_REQ";
export const STUDENTS_BY_GRADE_SUCCESS = "STUDENTS_BY_GRADE_SUCCESS";
export const STUDENTS_BY_GRADE_FAIL = "STUDENTS_BY_GRADE_FAIL";

export const STUDENTS_BY_CLASS_REQ = "STUDENTS_BY_CLASS_REQ";
export const STUDENTS_BY_CLASS_SUCCESS = "STUDENTS_BY_CLASS_SUCCESS";
export const STUDENTS_BY_CLASS_FAIL = "STUDENTS_BY_CLASS_FAIL";

export const ADD_STUDENT_REQ = "ADD_STUDENT_REQ";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";
export const ADD_STUDENT_RESET = "ADD_STUDENT_RESET";

export const DETAIL_STUDENT_REQ = "DETAIL_STUDENT_REQ";
export const DETAIL_STUDENT_SUCCESS = "DETAIL_STUDENT_SUCCESS";
export const DETAIL_STUDENT_FAIL = "DETAIL_STUDENT_FAIL";
export const DETAIL_STUDENT_RESET = "DETAIL_STUDENT_RESET";

export const UP_STUDENT_REQ = "UP_STUDENT_REQ";
export const UP_STUDENT_SUCCESS = "UP_STUDENT_SUCCESS";
export const UP_STUDENT_FAIL = "UP_STUDENT_FAIL";
export const UP_STUDENT_RESET = "UP_STUDENT_RESET";

export const DEL_STUDENT_REQ = "DEL_STUDENT_REQ";
export const DEL_STUDENT_SUCCESS = "DEL_STUDENT_SUCCESS";
export const DEL_STUDENT_FAIL = "DEL_STUDENT_FAIL";
export const DEL_STUDENT_RESET = "DEL_STUDENT_RESET";

export const UPLOAD_STUDENTS_REQ = "UPLOAD_STUDENTS_REQ";
export const UPLOAD_STUDENTS_SUCCESS = "UPLOAD_STUDENTS_SUCCESS";
export const UPLOAD_STUDENTS_FAIL = "UPLOAD_STUDENTS_FAIL";
export const UPLOAD_STUDENTS_RESET = "UPLOAD_STUDENTS_RESET";
