export const TEACHER_GET_REQ = "TEACHER_GET_REQ";
export const TEACHER_GET_SUCCESS = "TEACHER_GET_SUCCESS";
export const TEACHER_GET_FAIL = "TEACHER_GET_FAIL";

export const ADD_TEACHER_REQ = "ADD_TEACHER_REQ";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_FAIL = "ADD_TEACHER_FAIL";
export const ADD_TEACHER_RESET = "ADD_TEACHER_RESET";

export const UPLOAD_TEACHER_REQ = "UPLOAD_TEACHER_REQ";
export const UPLOAD_TEACHER_SUCCESS = "UPLOAD_TEACHER_SUCCESS";
export const UPLOAD_TEACHER_FAIL = "UPLOAD_TEACHER_FAIL";
export const UPLOAD_TEACHER_RESET = "UPLOAD_TEACHER_RESET";

export const UP_TEACHER_REQ = "UP_TEACHER_REQ";
export const UP_TEACHER_SUCCESS = "UP_TEACHER_SUCCESS";
export const UP_TEACHER_FAIL = "UP_TEACHER_FAIL";
export const UP_TEACHER_RESET = "UP_TEACHER_RESET";

export const DETAIL_TEACHER_REQ = "DETAIL_TEACHER_REQ";
export const DETAIL_TEACHER_SUCCESS = "DETAIL_TEACHER_SUCCESS";
export const DETAIL_TEACHER_FAIL = "DETAIL_TEACHER_FAIL";
export const DETAIL_TEACHER_RESET = "DETAIL_TEACHER_RESET";

export const DEL_TEACHER_REQ = "DEL_TEACHER_REQ";
export const DEL_TEACHER_SUCCESS = "DEL_TEACHER_SUCCESS";
export const DEL_TEACHER_FAIL = "DEL_TEACHER_FAIL";
export const DEL_TEACHER_RESET = "DEL_TEACHER_RESET";
