export const TEACHER_GET_REQ = "TEACHER_GET_REQ";
export const TEACHER_GET_SUCCESS = "TEACHER_GET_SUCCESS";
export const TEACHER_GET_FAIL = "TEACHER_GET_FAIL";

export const ADD_TEACHER_REQ = "ADD_TEACHER_REQ";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_FAIL = "ADD_TEACHER_FAIL";
export const ADD_TEACHER_RESET = "ADD_TEACHER_RESET";

export const UPLOAD_TEACHER_REQ = "UPLOAD_TEACHER_REQ";
export const UPLOAD_TEACHER_SUCCESS = "UPLOAD_TEACHER_SUCCESS";
export const UPLOAD_TEACHER_FAIL = "UPLOAD_TEACHER_FAIL";
export const UPLOAD_TEACHER_RESET = "UPLOAD_TEACHER_RESET";
