export const GET_CLASS_REQ = "GET_CLASS_REQ";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const GET_CLASS_FAIL = "GET_CLASS_FAIL";

export const ADD_CLASS_REQ = "ADD_CLASS_REQ";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAIL = "ADD_CLASS_FAIL";
export const ADD_CLASS_RESET = "ADD_CLASS_RESET";

export const DELETE_CLASS_REQ = "DELETE_CLASS_REQ";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";
export const DELETE_CLASS_RESET = "DELETE_CLASS_RESET";
